<?php

/*
 * This file is part of the WP Starter package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace WeCodeMore\WpStarter\Util;

use WeCodeMore\WpStarter\Config\Config;
use WeCodeMore\WpStarter\Io\Io;
use WeCodeMore\WpStarter\Step\OptionalStep;

/**
 * Collaborator to serve steps that generate files and might need to overwrite them.
 *
 * This helper ease the task of deciding what to do in case a file that is generated by a step needs
 * exists already. WP Starter provides a global configuration for how to deal with existing files.
 * Based on that configuration steps might not be allowed to overwrite files, or might need to ask
 * the user for confirmation. This class allows to do that very easily for all steps without warring
 * about details.
 */
class OverwriteHelper
{
    /** @var "ask"|array<string>|bool */
    private $preventFor; // phpcs:ignore
    private Io $io;
    private string $root;
    private \Composer\Util\Filesystem $filesystem;

    /**
     * @param Config $config
     * @param Io $io
     * @param string $root
     * @param \Composer\Util\Filesystem $filesystem
     */
    public function __construct(
        Config $config,
        Io $io,
        string $root,
        \Composer\Util\Filesystem $filesystem
    ) {

        /** @var OptionalStep::ASK|array<string>|bool $preventForConfig */
        $preventForConfig = $config[Config::PREVENT_OVERWRITE]->unwrapOrFallback(false);
        $this->preventFor = $preventForConfig;

        if (is_array($this->preventFor)) {
            $preventFor = [];
            foreach ($this->preventFor as $path) {
                $preventFor[] = trim($filesystem->normalizePath($path), '/');
            }
            $this->preventFor = $preventFor;
        }
        $this->io = $io;
        $this->root = $filesystem->normalizePath($root);
        $this->filesystem = $filesystem;
    }

    /**
     * Return true if a file does not exist or exists but should be overwritten according to config.
     * Ask user if necessary.
     *
     * @param string $file
     * @return bool
     */
    public function shouldOverwrite(string $file): bool
    {
        if (is_dir($file)) {
            return false;
        }

        if (!is_file($file)) {
            return true;
        }

        $path = $this->filesystem->normalizePath($file);

        if ($this->preventFor === OptionalStep::ASK) {
            $name = basename($file);
            $lines = ["{$name} found in target folder", 'Do you want to overwrite it?'];

            return $this->io->askConfirm($lines, true);
        }

        if (is_array($this->preventFor)) {
            preg_match('#^' . preg_quote($this->root, '#') . '/(.+)#', $path, $matches);
            if (!isset($matches[1])) {
                return false;
            }

            $relative = trim($matches[1], '/');

            return $this->patternCheck($relative, $this->preventFor);
        }

        return !$this->preventFor;
    }

    /**
     * Check if a file is set to not be overwritten using shell patterns.
     *
     * @param string $path
     * @param array<mixed> $patterns
     * @return bool
     */
    private function patternCheck(string $path, array $patterns): bool
    {
        $overwrite = true;
        while (($overwrite === true) && ($patterns !== [])) {
            $pattern = array_shift($patterns);
            $overwrite = is_string($pattern) && !fnmatch($pattern, $path, FNM_NOESCAPE);
        }

        return $overwrite;
    }
}
