<?php
/**
 * This file is generated by WP Starter Package, and contains base configurations of the WordPress.
 *
 * All the configuration constants used by WordPress are set via .env file.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 * A sample .env file (.env.example) should be placed in the root of your project, rename it to .env
 * and edit it according to your needs.
 */

/**
 * Composer autoload.
 */
require_once realpath(dirname(__DIR__).'/vendor'.'/autoload.php');

/**
 * Configuration constants.
 *
 * Use .env file to set WordPress constants.
 * Mandatory settings:
 * - DB_NAME
 * - DB_USER
 * - DB_PASSWORD
 *
 * @var array $env All the variables stored in .env file
 */
$env = WCM\WPStarter\Helpers::settings(dirname(__DIR__), '.env');
array_walk($env, function ($value, $name) {
    switch ($name) {
        case 'DB_TABLE_PREFIX':
            $GLOBALS['table_prefix'] = preg_replace('#[^\w]#', '', $value);
            break;
        default:
            defined($name) or define($name, $value);
            break;
    }
});

/**
 * Set optional database settings if not already set
 */
defined('DB_HOST')    or define('DB_HOST',    'localhost');
defined('DB_CHARSET') or define('DB_CHARSET', 'utf8');
defined('DB_COLLATE') or define('DB_COLLATE', '');

/**
 * Set WordPress Database Table prefix if not already set.
 *
 * @global string $table_prefix
 */
if (! isset($table_prefix) || empty($table_prefix)) {
    $table_prefix = 'wp_';
}

/**
 * Set unique authentication keys if not already set via .env file.
 * If available, environment name is mixed to keys so they become unique per environment.
 */
$environment = getenv('WORDPRESS_ENV');
$pre = $environment  ? substr($environment, 0, 5)  : substr('T:;kk1QD#ww6~y6Tu.(S,z$GR)@VvgV)nO~s/qZ=Q|m03FKoZ3y~,%', 0, 5);
$post = $environment ? substr($environment, -5, 5) : substr('{WeXmGWNg~.$V40gyXn+TtUO=:_c%Q)afmh>>Lnj#`&0os+.mODloY', 0, 5);
defined('AUTH_KEY')         or define('AUTH_KEY',         $pre.'T:;kk1QD#ww6~y6Tu.(S,z$GR)@VvgV)nO~s/qZ=Q|m03FKoZ3y~,%'.$post);
defined('SECURE_AUTH_KEY')  or define('SECURE_AUTH_KEY',  $pre.'{WeXmGWNg~.$V40gyXn+TtUO=:_c%Q)afmh>>Lnj#`&0os+.mODloY'.$post);
defined('LOGGED_IN_KEY')    or define('LOGGED_IN_KEY',    $pre.'YGXogR.BNcRId@6G*ZMndJ7>9Y<<}Z!C[Hl8[<H<08UdOOGXvdPm73'.$post);
defined('NONCE_KEY')        or define('NONCE_KEY',        $pre.'+&#mB_xqCj~R~:>K2;PhO}Ra{[dhYu!`!4X].5!?WzjSkk[(.5x0|o'.$post);
defined('AUTH_SALT')        or define('AUTH_SALT',        $pre.'7gEFM[M&L);KJ8WjNGDrvwJpKF$zQy1XMF}m;1pAGu6`OjLV{gJ-,K'.$post);
defined('SECURE_AUTH_SALT') or define('SECURE_AUTH_SALT', $pre.'2?~1Cq>?yO[.U=V3~@*SBR-uxk^mk/;/Gbw&R>[opH%:FR-P4X1]}w'.$post);
defined('LOGGED_IN_SALT')   or define('LOGGED_IN_SALT',   $pre.'Q{LG)5!2nN@OM=/`u<eB9>b|`I:G>FQlV&dJ`#O@Ar3&3HaPt2e=>g'.$post);
defined('NONCE_SALT')       or define('NONCE_SALT',       $pre.'eyx63[ATqk~(v%g#.kg[sYgc2DSxOiKTk#O}/r~B%wNlG?oOJ7L5%J'.$post);

/**
 * Environment-aware settings. Be creative, but avoid to set sensitive settings here.
 */
switch ($environment) {

    case 'development':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        defined('SAVEQUERIES')      or define('SAVEQUERIES',      true);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     true);
        break;

    case 'staging':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     true);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     true);
        break;

    case 'production':
    default:
        defined('WP_DEBUG')         or define('WP_DEBUG',         false);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        defined('SCRIPT_DEBUG')     or define('SCRIPT_DEBUG',     false);
        break;
}

/**
 * Fix HTTPS behind load balancers.
 *
 * @link https://core.trac.wordpress.org/ticket/31288
 * @link https://github.com/wecodemore/wpstarter/issues/7
 */
if (
    isset($_SERVER['HTTP_X_FORWARDED_PROTO'])
	&& 'https' === strtolower($_SERVER['HTTP_X_FORWARDED_PROTO'])
) {
	$_SERVER[ 'HTTPS' ] = 'on';
}

/**
 * Set WordPress paths and urls if not set via .env file.
 */
if (! defined('WP_HOME')) {
    $server = filter_input_array(INPUT_SERVER, array(
        'HTTPS'       => FILTER_SANITIZE_STRING,
        'SERVER_PORT' => FILTER_SANITIZE_NUMBER_INT,
        'SERVER_NAME' => FILTER_SANITIZE_URL,
    ));
    $secure = in_array((string) $server['HTTPS'], array('on', '1'), true);
    $scheme = $secure ? 'https://' : 'http://';
    $name   = $server['SERVER_NAME'] ? : 'localhost';
    define('WP_HOME', $scheme.$name);
}
defined('ABSPATH')        or define('ABSPATH',        realpath(dirname(__DIR__).'/public\wp'));
defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(dirname(__DIR__).'/'));
defined('WP_SITEURL')     or define('WP_SITEURL',     rtrim(WP_HOME, '/').'/wp');
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/').'/');

/**
 * Clean up.
 */
unset($env, $environment, $pre, $post, $server, $secure, $scheme, $name);

/**
 * Allows to load MU plugins in subfolders.
 */
WCM\WPStarter\Helpers::addHook(
    'muplugins_loaded',
    new WCM\WPStarter\MuLoader\MuLoader(),
    PHP_INT_MAX,
    0
);

/**
 * Register default themes inside WordPress package wp-content folder.
 */
WCM\WPStarter\Helpers::addHook('plugins_loaded', function () {
    WCM\WPStarter\Helpers::loadThemeFolder(true);
}, 0);

/**
 * Sets up WordPress vars and included files.
 */
require_once ABSPATH.DIRECTORY_SEPARATOR.'wp-settings.php';
