<?php

/**
 * This file is generated by WP Starter package, and contains base configuration of the WordPress.
 *
 * All the configuration constants used by WordPress are set via environment variables.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 *
 * This is a proxy to the actual configuration file at: {{{WP_CONFIG_PATH}}}.
 */

/*
WP CLI uses regexp to parse the expected wp-config.php, then it eval the code in it, skipping
one line that requires WP settings file.
We are going to cheat WP CLI while singing "ob-la-di, ob-la-da life goes on, brah".

Desmond takes a trolley to the jeweler's store
Buys a 20-carat golden ring (ring)
Takes it back to Molly waiting at the door
And as he gives it to her, she begins to sing (sing)
Ob-la-di, ob-la-da (la, la, la, la, la, la)
Life goes on, brah (la, la, la, la, la, la)
La, la, how the life goes on.

require wp-settings.php
*/

const WP_STARTER_WP_CONFIG_PATH = __DIR__ . '{{{WP_CONFIG_PATH}}}';

require realpath(__DIR__ . '{{{WP_CONFIG_PATH}}}');
