<?php
/**
 * This file is generated by WP Starter package, and contains base configuration of the WordPress.
 *
 * All the configuration constants used by WordPress are set via environment variables.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 *
 */
use WeCodeMore\WpStarter\Env\WordPressEnvBridge;

/** Composer autoload. */
require_once realpath(__DIR__ . '{{{AUTOLOAD_PATH}}}');

/** A reference to `.env` folder path. */
define('WPSTARTER_PATH', realpath(__DIR__ . '{{{ENV_REL_PATH}}}'));

/**
 * Define all WordPress constants from environment variables.
 * Environment variables will be loaded from file, unless `WPSTARTER_ENV_LOADED` env var is already
 * setup e.g. via webserver configuration.
 * In that case all environment variables are assumed to be set.
 * Environment variables that are set in the *real* environment (e.g. via webserver) will not be
 * overridden from file, even if `WPSTARTER_ENV_LOADED` is not set.
 */
$envLoader = new WordPressEnvBridge();
$envLoader->load('{{{ENV_FILE_NAME}}}', WPSTARTER_PATH);
$env = $envLoader->read('WP_ENV') ?? $envLoader->read('WORDPRESS_ENV');
if ($env && $env !== 'example') {
    $envLoader->loadAppended("{{{ENV_FILE_NAME}}}.{$env}", WPSTARTER_PATH);
}
$envKeys = $envLoader->setupWordPress();

/** Set optional database settings if not already set. */
$envKeys['DB_HOST'] ?? define('DB_HOST', 'localhost');
$envKeys['DB_CHARSET'] ?? define('DB_CHARSET', 'utf8');
$envKeys['DB_COLLATE'] ?? define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 */
$envKeys['AUTH_KEY'] ?? define('AUTH_KEY', '{{{AUTH_KEY}}}');
$envKeys['SECURE_AUTH_KEY'] ?? define('SECURE_AUTH_KEY', '{{{SECURE_AUTH_KEY}}}');
$envKeys['LOGGED_IN_KEY'] ?? define('LOGGED_IN_KEY', '{{{LOGGED_IN_KEY}}}');
$envKeys['NONCE_KEY'] ?? define('NONCE_KEY', '{{{NONCE_KEY}}}');
$envKeys['AUTH_SALT'] ?? define('AUTH_SALT', '{{{AUTH_SALT}}}');
$envKeys['SECURE_AUTH_SALT'] ?? define('SECURE_AUTH_SALT', '{{{SECURE_AUTH_SALT}}}');
$envKeys['LOGGED_IN_SALT'] ?? define('LOGGED_IN_SALT', '{{{LOGGED_IN_SALT}}}');
$envKeys['NONCE_SALT'] ?? define('NONCE_SALT', '{{{NONCE_SALT}}}');
unset($envKeys);

/**#@-*/

/**
 * WordPress Database Table prefix.
 */
global $table_prefix;
empty($table_prefix) or $table_prefix = 'wp_';

/** Absolute path to the WordPress directory. */
define('ABSPATH', realpath(__DIR__ . '{{{WP_INSTALL_PATH}}}') . '/');

/** Load plugin.php early, so we can call `add_action` below. */
require_once ABSPATH . 'wp-includes/plugin.php';

/** Environment-aware settings. Be creative, but avoid having sensitive settings here. */
if ($env
    && file_exists("{{{ENV_BOOTSTRAP_DIR}}}{$env}.php")
    && is_readable("{{{ENV_BOOTSTRAP_DIR}}}{$env}.php")
) {
    require_once "{{{ENV_BOOTSTRAP_DIR}}}{$env}.php";
}
switch ($env) {
    case 'development':
        defined('WP_DEBUG') or define('WP_DEBUG', true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', false);
        defined('SAVEQUERIES') or define('SAVEQUERIES', true);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', true);
        break;
    case 'staging':
        defined('WP_DEBUG') or define('WP_DEBUG', true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', true);
        defined('SAVEQUERIES') or define('SAVEQUERIES', false);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', true);
        break;
    case 'production':
    default:
        defined('WP_DEBUG') or define('WP_DEBUG', false);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG') or define('WP_DEBUG_LOG', false);
        defined('SAVEQUERIES') or define('SAVEQUERIES', false);
        defined('SCRIPT_DEBUG') or define('SCRIPT_DEBUG', false);
        break;
}

/** Fix `is_ssl()` behind load balancers. */
if ($envLoader->read('WP_FORCE_SSL_FORWARDED_PROTO')
    && array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER)
    && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https'
) {
    $_SERVER['HTTPS'] = 'on';
}

/**
 * Load early hooks file if any.
 * Early hooks file allows to add hooks that are triggered before plugins are loaded, e.g.
 * "enable_loading_advanced_cache_dropin" or to just-in-time define configuration constants.
 */
if ('{{{EARLY_HOOKS_FILE}}}'
    && file_exists('{{{EARLY_HOOKS_FILE}}}')
    && is_readable('{{{EARLY_HOOKS_FILE}}}')
) {
    require_once '{{{EARLY_HOOKS_FILE}}}';
}

/** Set WordPress content constants if not set via environment variables. */
defined('WP_HOME') or define('WP_HOME', set_url_scheme(($_SERVER['SERVER_NAME'] ?? '') ?: 'localhost'));
defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(__DIR__ . '{{{WP_CONTENT_PATH}}}'));
defined('WP_SITEURL') or define('WP_SITEURL', rtrim(WP_HOME, '/') . '/{{{WP_SITEURL_RELATIVE}}}');
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/') . '/{{{WP_CONTENT_URL_RELATIVE}}}');

/** Register default themes inside WordPress package wp-content folder. */
if (filter_var('{{{REGISTER_THEME_DIR}}}', FILTER_VALIDATE_BOOLEAN)) {
    add_action(
        'plugins_loaded',
        function () {
            register_theme_directory(ABSPATH . 'wp-content/themes');
        },
        0
    );
}

/** Allow changing admin color scheme. Useful to distinguish environments in the dashboard. */
$forceAdminColor = $envLoader->read('WP_ADMIN_COLOR');
add_filter(
    'get_user_option_admin_color',
    function ($color) use ($forceAdminColor) {
        return $forceAdminColor ?: $color;
    },
    999
);

unset($env, $envLoader, $forceAdminColor);

###################################################################################################
#  I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion.  #
#                 I watched C-beams glitter in the dark near the Tannhauser gate.                 #
#            All those moments will be lost in time, like tears in rain. Time to die.             #
###################################################################################################

/* That's all, stop editing! Happy blogging. */

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
