<?php
/**
 * This file is generated by WP Starter Package, and contains base configurations of the WordPress.
 *
 * All the configuration constants used by WordPress are set via .env file.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 * A sample .env file (.env.example) should be placed in the root of your project, rename it to .env
 * and edit it according to your needs.
 */

/**
 * Composer autoload.
 */
require_once realpath(__DIR__.'/{{{VENDOR_PATH}}}/autoload.php');

/**
 * Configuration constants.
 *
 * Use .env file to set WordPress constants.
 * Mandatory settings:
 * - DB_NAME
 * - DB_USER
 * - DB_PASSWORD
 *
 * @var array $env All the variables stored in .env file
 */
$env = WCM\WPStarter\Helpers::settings(__DIR__);
array_walk($env, function ($value, $name) {
    switch ($name) {
        case 'WORDPRESS_ENV':
            // NOT one more global variable for WP: it will be unset before this file ends
            $GLOBALS['environment'] = $value;
            break;
        case 'DB_TABLE_PREFIX':
            $GLOBALS['table_prefix'] = preg_replace('#[^\w]#', '', $value);
            break;
        default :
            define($name, $value);
            break;
    }
});

/**
 * Set optional database settings if not already set
 */
defined('DB_HOST')    or define('DB_HOST',    'localhost');
defined('DB_CHARSET') or define('DB_CHARSET', 'utf8');
defined('DB_COLLATE') or define('DB_COLLATE', '');

/**
 * Set WordPress Database Table prefix if not already set.
 *
 * @global string $table_prefix
 */
if (! isset($table_prefix) || empty($table_prefix)) {
    $table_prefix = 'wp_';
}

/**
 * Set unique authentication keys if not already set via .env file.
 * If available, environment name is mixed to keys so they become unique per environment.
 */
global $environment;
$pre = $environment  ? substr($environment, 0, 5)  : substr('{{{AUTH_KEY}}}', 0, 5);
$post = $environment ? substr($environment, -5, 5) : substr('{{{SECURE_AUTH_KEY}}}', 0, 5);
defined('AUTH_KEY')         or define('AUTH_KEY',         $pre.'{{{AUTH_KEY}}}'.$post);
defined('SECURE_AUTH_KEY')  or define('SECURE_AUTH_KEY',  $pre.'{{{SECURE_AUTH_KEY}}}'.$post);
defined('LOGGED_IN_KEY')    or define('LOGGED_IN_KEY',    $pre.'{{{LOGGED_IN_KEY}}}'.$post);
defined('NONCE_KEY')        or define('NONCE_KEY',        $pre.'{{{NONCE_KEY}}}'.$post);
defined('AUTH_SALT')        or define('AUTH_SALT',        $pre.'{{{AUTH_SALT}}}'.$post);
defined('SECURE_AUTH_SALT') or define('SECURE_AUTH_SALT', $pre.'{{{SECURE_AUTH_SALT}}}'.$post);
defined('LOGGED_IN_SALT')   or define('LOGGED_IN_SALT',   $pre.'{{{LOGGED_IN_SALT}}}'.$post);
defined('NONCE_SALT')       or define('NONCE_SALT',       $pre.'{{{NONCE_SALT}}}'.$post);

/**
 * Environment aware settings. Be creative, but avoid to set sensitive settings here.
 */
switch ($environment) {

    case 'development':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        break;

    case 'staging':
        defined('WP_DEBUG')         or define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     true);
        break;

    case 'production':
    default:
        defined('WP_DEBUG')         or define('WP_DEBUG',         false);
        defined('WP_DEBUG_DISPLAY') or define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     or define('WP_DEBUG_LOG',     false);
        break;
}

/**
 * Set WordPress paths and urls if not set via .env file.
 */
if (! defined('WP_HOME')) {
    $server = filter_input_array(INPUT_SERVER, array(
        'HTTPS'       => FILTER_SANITIZE_STRING,
        'SERVER_PORT' => FILTER_SANITIZE_NUMBER_INT,
        'SERVER_NAME' => FILTER_SANITIZE_URL,
    ));
    define('WP_HOME', (
        (! empty($server['HTTPS']) && in_array((string) $server['HTTPS'], array('on', '1'), true))
        || (int) $server['SERVER_PORT'] === 443
            ? 'https://'
            : 'http://'
        ).$server['SERVER_NAME']);
}
defined('ABSPATH')        or define('ABSPATH',        realpath(__DIR__.'/{{{WP_INSTALL_PATH}}}'));
defined('WP_CONTENT_DIR') or define('WP_CONTENT_DIR', realpath(__DIR__.'/{{{WP_CONTENT_PATH}}}'));
defined('WP_SITEURL')     or define('WP_SITEURL',     rtrim(WP_HOME, '/').'/{{{WP_INSTALL_PATH}}}');
defined('WP_CONTENT_URL') or define('WP_CONTENT_URL', rtrim(WP_HOME, '/').'/{{{WP_CONTENT_PATH}}}');

/**
 * Clean up.
 */
unset($env, $environment, $pre, $post, $server);

/**
 * Allow to load MU plugins in subfolders.
 */
WCM\WPStarter\Helpers::addHook('muplugins_loaded', new WCM\WPStarter\MuLoader(), PHP_INT_MAX, 0);

/**
 * Sets up WordPress vars and included files.
 */
require_once ABSPATH.'/wp-settings.php';
